### ISSUE TITLE
query g 

### ISSUE THREAD

**Issue by BonShillings** [navies/databases-project#7]
query is returning results when it shouldn't 

the following is being displayed 

name	rtype	phone_number	
Fauna	Canadian	613-680-8803
The Albion Rooms	Canadian	613-649-6479
Clover Food	Canadian	613-265-4501
Cacao70	Desert	613-987-6543
Big Smoke Burger	American	613-416-4169
SuzyQ	Desert	613-420-0240
Union Local 613	Southern	613-111-1111
The Smoque Shack	American	613-123-4567
MLT DWN	Canadian	613-235-7110
Union Local 613	Southern	613-000-0000

when no results should be returned

**Comment by navies** [comment]
Query is working intended. All of those restaurants have a rating with a date from -2015-01-XX-

**Comment by navies** [comment]
Query is working as intended. Those restaurants do NOT have a rating with a date in '2015-01-XX'.

**Comment by BonShillings** [comment]
ahh kk i should have read the query description
